### ISSUE TITLE
The real MVP

### ISSUE THREAD

**Issue by xxnatc** [xaviers-school/real-time-911-seattle#22]
Here's a list of features to be implemented before deployment:
- [ ] #14 - scraper and database
- [ ] #8 - filtering and map update
- [x] #17 - sidebar: chronological list of entries
- [ ] #21 - uniform map pin icons
- [ ] #27 - click entry and focus to the corresponding pin on map
- [x] #28 - generate query and API endpoints

Stretches 1:
1. #6 - recognize user location
2. #9, #10 - radius bubble + alerts

Stretches 2:
1. #7 - hide address and location for sensitive incidents
2. #20 - upload content of specific incidents
